export const FilterOptions = [
  {
    id: '1',
    name: 'Heart',
    typeComponent: 'icon',
    value: false,
  },
  {
    id: '2',
    name: 'Owned',
    typeComponent: 'switch',
    value: false,
  },
  {
    id: '3',
    name: 'Your Order',
    typeComponent: 'switch',
    value: false,
  },
  {
    id: '4',
    name: 'Price range',
    typeComponent: 'slider',
    variants: 'type-1',
    value: [0, 100],
  },
  {
    id: '5',
    name: 'Character',
    options: [
      {
        id: '5.1',
        name: 'Hyper',
        valueColor: '#F41C24',
        typeComponents: 'button',
        variants: 'hasIcon',
        value: false,
      },
      {
        id: '5.2',
        name: 'Rocket',
        valueColor: '#0A70CB',
        typeComponents: 'button',
        variants: 'hasIcon',
        value: false,
      },
      {
        id: '5.3',
        name: 'Blaster',
        valueColor: '#87E321',
        variants: 'hasIcon',
        typeComponents: 'button',
        value: false,
      },
    ],
    rarity: [
      {
        id: '5.4',
        name: 'Common',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '5.5',
        name: 'Uncommon',
        valueColor: '#7AA0D6',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '5.6',
        name: 'Rare',
        valueColor: '#B3D9A1',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '5.7',
        name: 'Epic',
        valueColor: '#9634F8',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '5.8',
        name: 'Legend',
        valueColor: '#F7B16F',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '5.9',
        name: 'Mystic',
        valueColor: '#FB3434',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
    ],
  },
  {
    id: '6',
    name: 'Gem',
    options: [
      {
        id: '6.1',
        name: 'circle',
        valueImage: '/images/Filter/circle.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '6.2',
        name: 'triangle',
        valueImage: '/images/Filter/circle.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '6.3',
        name: 'square',
        valueImage: '/images/Filter/square.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '6.4',
        name: 'rhombus-small',
        valueImage: '/images/Filter/rhombus-small.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '6.5',
        name: 'rhombus-medium',
        valueImage: '/images/Filter/rhombus-medium.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '6.6',
        name: 'rhombus-large',
        valueImage: '/images/Filter/rhombus-large.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
    ],
    rarity: [
      {
        id: '6.7',
        name: 'Common',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '6.8',
        name: 'Uncommon',
        valueColor: '#7AA0D6',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '6.9',
        name: 'Rare',
        valueColor: '#B3D9A1',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '6.10',
        name: 'Epic',
        valueColor: '#9634F8',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '6.11',
        name: 'Legend',
        valueColor: '#F7B16F',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '6.12',
        name: 'Mystic',
        valueColor: '#FB3434',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
    ],
    level: {
      id: '6.13',
      name: 'Level',
      typeComponent: 'slider',
      variants: 'type-2',
      value: [0, 100],
    },
  },
  {
    id: '7',
    name: 'Talent',
    typeComponent: 'search',
    value: '',
  },
  {
    id: '8',
    name: 'Gun',
    options: [
      {
        id: '8.1',
        name: 'Pistol',
        valueColor: '#F41C24',
        typeComponents: 'button',
        variants: 'hasIcon',
        value: false,
      },
      {
        id: '8.2',
        name: 'Rifle',
        valueColor: '#0A70CB',
        typeComponents: 'button',
        variants: 'hasIcon',
        value: false,
      },
      {
        id: '8.3',
        name: 'Cannon',
        valueColor: '#87E321',
        typeComponents: 'button',
        variants: 'hasIcon',
        value: false,
      },
      {
        id: '8.4',
        name: 'Laser',
        valueColor: '#0A70CB',
        typeComponents: 'button',
        variants: 'hasIcon',
        value: false,
      },
      {
        id: '8.5',
        name: 'Shotgun',
        valueColor: '#87E321',
        typeComponents: 'button',
        variants: 'hasIcon',
        value: false,
      },
      {
        id: '8.6',
        name: 'Special',
        valueColor: '#0A70CB',
        typeComponents: 'button',
        variants: 'hasIcon',
        value: false,
      },
    ],
    rarity: [
      {
        id: '8.7',
        name: 'Common',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '8.8',
        name: 'Uncommon',
        valueColor: '#7AA0D6',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '8.9',
        name: 'Rare',
        valueColor: '#B3D9A1',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '8.10',
        name: 'Epic',
        valueColor: '#9634F8',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '8.11',
        name: 'Legend',
        valueColor: '#F7B16F',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
      {
        id: '8.12',
        name: 'Mystic',
        valueColor: '#FB3434',
        typeComponents: 'button',
        variants: 'hasColor',
        value: false,
      },
    ],
    stats: [
      {
        id: '8.13',
        name: 'Gun Attack',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.14',
        name: 'Gun Damage',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.15',
        name: 'Bullet Range',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.16',
        name: 'Gun Magazine',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.17',
        name: 'Gun Reload Time',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.18',
        name: 'Gunfire Shoot Speed',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.19',
        name: 'Repeat Bullet Number',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.20',
        name: 'Gun Charger Delay',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.21',
        name: 'Ray Width',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.22',
        name: 'Explosion Damage Range',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.23',
        name: 'Single Fire Bullet Number',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.24',
        name: 'Number of Laser Link',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.25',
        name: 'Flame Width',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
      {
        id: '8.26',
        name: 'Aiming Time',
        typeComponent: 'slider',
        variants: 'type-2',
        value: [0, 100],
        isSelected: false,
      },
    ],
    'Bullet-Element': [
      {
        id: '8.27',
        name: 'Kinetic',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
      {
        id: '8.28',
        name: 'Electric',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
      {
        id: '8.29',
        name: 'Flame',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
      {
        id: '8.30',
        name: 'Frost',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
      {
        id: '8.31',
        name: 'Venom',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
    ],
    'Star-Rank': {
      id: '8.32',
      name: 'Star Rank',
      typeComponents: 'rating',
      value: 0,
    },
  },
  {
    id: '9',
    name: 'Plug-in',
    options: [
      {
        id: '9.1',
        name: 'plugin-1',
        valueImage: '/images/Filter/plugin-1.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '9.2',
        name: 'plugin-2',
        valueImage: '/images/Filter/plugin-2.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '9.3',
        name: 'plugin-3',
        valueImage: '/images/Filter/plugin-3.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '9.4',
        name: 'plugin-4',
        valueImage: '/images/Filter/plugin-4.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '9.5',
        name: 'plugin-5',
        valueImage: '/images/Filter/plugin-5.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
      {
        id: '9.6',
        name: 'plugin-6',
        valueImage: '/images/Filter/plugin-6.png',
        typeComponents: 'button',
        variants: 'onlyIcon',
        value: false,
      },
    ],
    rank: {
      id: '9.7',
      name: 'Star',
      typeComponents: 'rating',
      value: 0,
    },
    status: [
      {
        id: '9.8',
        name: 'For Sale',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
      {
        id: '9.9',
        name: 'Not For Sale',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
    ],
  },
  {
    id: '10',
    name: 'Status',
    options: [
      {
        id: '10.1',
        name: 'For Sale',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
      {
        id: '10.2',
        name: 'Not For Sale',
        valueColor: '#FFFFFF',
        typeComponents: 'button',
        variants: 'hasNotColor',
        value: false,
      },
    ],
  },
];
